version: '3.7'

services:

  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '~/.composer-docker/cache:/root/.composer/cache:delegated'
      - './:/usr/src/app:cached'
    
    ports:
      - '8081:8080'